potential solution for local data storage
Wilsonator123/BankingApp pull request #37
Opened 2024-07-17 21:08 UTC by perry-C

@Wilsonator123 Take a look tomorrow and tell me what you think

some ref:
https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-8.0
https://stackoverflow.com/questions/19280555/what-is-the-best-way-to-store-data-in-c-sharp-application
...

2024-07-18 06:50 UTC, Josephaguele commented
@perry-C thank you for your research. Although, I checked through the links and I can't really find where your solution was derived from. May be when we test it when we have a meeting later on today.

2024-07-18 11:44 UTC, Wilsonator123 commented
> @Wilsonator123 Take a look tomorrow and tell me what you think
> 
> some ref: https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-8.0 https://stackoverflow.com/questions/19280555/what-is-the-best-way-to-store-data-in-c-sharp-application ...

I get the idea but i dont think this is the way forward. what would be better is something similar to this:

```CSharp
string currentDirectory = Directory.GetCurrentDirectory();
string relativePath = Path.Combine(currentDirectory, @"..\..\bin\my_executable.exe");
```

2024-07-18 11:54 UTC, perry-C commented
> > @Wilsonator123 Take a look tomorrow and tell me what you think
> > some ref: https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-8.0 https://stackoverflow.com/questions/19280555/what-is-the-best-way-to-store-data-in-c-sharp-application ...
> 
> I get the idea but i dont think this is the way forward. what would be better is something similar to this:
> 
> ```cs
> string currentDirectory = Directory.GetCurrentDirectory();
> string relativePath = Path.Combine(currentDirectory, @"..\..\bin\my_executable.exe");
> 
> // or 
> 
> string currentDirectory = Directory.GetCurrentDirectory();
> string relativePath = Path.Combine(currentDirectory, @".\My_Project\repo1.exe");
> ```

Yeah this is kind of similar to what I did before, and it should work if you are solely **reading** local data. But if you want to write some new data under the project's directory, you are essentially writing to something that is running, I haven't tried it personally, but I dont think that will work.

2024-07-18 11:59 UTC, Wilsonator123 commented
> > > @Wilsonator123 Take a look tomorrow and tell me what you think
> > > some ref: https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-8.0 https://stackoverflow.com/questions/19280555/what-is-the-best-way-to-store-data-in-c-sharp-application ...
> > 
> > 
> > I get the idea but i dont think this is the way forward. what would be better is something similar to this:
> > ```cs
> > string currentDirectory = Directory.GetCurrentDirectory();
> > string relativePath = Path.Combine(currentDirectory, @"..\..\bin\my_executable.exe");
> > 
> > // or 
> > 
> > string currentDirectory = Directory.GetCurrentDirectory();
> > string relativePath = Path.Combine(currentDirectory, @".\My_Project\repo1.exe");
> > ```
> 
> Yeah this is kind of similar to what I did before, and it should work if you are solely **reading** local data. But if you want to write some new data under the project's directory, you are essentially writing to something that is running, I haven't tried it personally, but I dont think that will work.

I kind of understand what you are saying, but I think this will work fine

2024-07-18 12:08 UTC, perry-C commented
Ok found it here is the link https://www.codeproject.com/Tips/370232/Where-Should-I-Store-My-Data
![image](https://github.com/user-attachments/assets/5d4039e5-ce6e-42cd-b18f-baa6f1cac920)

2024-07-18 12:14 UTC, Wilsonator123 commented
> Ok found it here is the link https://www.codeproject.com/Tips/370232/Where-Should-I-Store-My-Data ![image](https://private-user-images.githubusercontent.com/55983397/349947433-5d4039e5-ce6e-42cd-b18f-baa6f1cac920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDQ4MTIsIm5iZiI6MTcyMTMwNDUxMiwicGF0aCI6Ii81NTk4MzM5Ny8zNDk5NDc0MzMtNWQ0MDM5ZTUtY2U2ZS00MmNkLWIxOGYtYmFhNmYxY2FjOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyMDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2M4NzY1Y2Q4NTFjNTVhNjFlN2RkNzUwYzQzMGI5YzBjM2U5YzgwNGQ2MWVlY2NjODRmYTNmMjZkMzI4NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.beRlkjAYxmewX_YeaT2aycAve8Zp0FASuql4NzVfhPo)

Ye i mean it looks good, just wont run it on my laptop :joy: 
If you can get this implemented nicely then i guess its all good!

2024-07-18 12:16 UTC, perry-C commented
Wait I remember now, are you using linux atm?

2024-07-18 12:22 UTC, Wilsonator123 commented
> > It won't? Ok that might be problematic. What does the error say?
> 
> Wait I remember now, are you using linux atm?

On my laptop I just moved to linux, my main PC is still windows

2024-07-18 12:23 UTC, perry-C commented
> > > It won't? Ok that might be problematic. What does the error say?
> > 
> > 
> > Wait I remember now, are you using linux atm?
> 
> On my laptop I just moved to linux, my main PC is still windows

Does it work on your main pc?

2024-07-18 12:55 UTC, Wilsonator123 commented
> > > > It won't? Ok that might be problematic. What does the error say?
> > > 
> > > 
> > > Wait I remember now, are you using linux atm?
> > 
> > 
> > On my laptop I just moved to linux, my main PC is still windows
> 
> Does it work on your main pc?

Sadly I on the coast of Norwich so won't be able to check till tomorrow.
If you solution works then carry on a get someone to test it

2024-07-18 16:48 UTC, perry-C commented
@Wilsonator123 Take a look, the new Method I wrote should be able to convert to Account object, although I will only work with business for now

2024-07-18 17:23 UTC, Wilsonator123 requested changes

2024-07-18 17:23 UTC, Wilsonator123 commented on Data.cs
> +            while ((line = sr.ReadLine()) != null)
Would this need to be turned into a dictionary and not just 

`line.Split(",")` then pass in the string[]

2024-07-18 17:25 UTC, Wilsonator123 commented on Data.cs
> +            while ((line = sr.ReadLine()) != null)
Both methods work but this seems a bit extra. You currently
string -> string[] -> dictionary -> Object 
string -> string[] -> Object

2024-07-18 17:28 UTC, perry-C commented on Data.cs
> +            while ((line = sr.ReadLine()) != null)
Yeah there definitely is optimisation work too be done, I was kind of dizzy while doing it

2024-07-18 17:32 UTC, perry-C commented on Data.cs
> +            while ((line = sr.ReadLine()) != null)
trying to go for speed over quality here haha

2024-07-19 12:59 UTC, Wilsonator123 approved these changes

2024-07-19 13:00 UTC, merged